import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

export const START = "<!-- idiolect:start -->";
export const END = "<!-- idiolect:end -->";
const NOTE = "<!-- Generated by idiolect. Do not edit between the markers, run idiolect sync to refresh. -->";

/** Known agent instruction files. Only AGENTS.md is created when missing, the rest are updated if they already exist. */
export const DEFAULT_TARGETS = ["AGENTS.md", "CLAUDE.md", ".cursor/rules/idiolect.mdc", ".github/copilot-instructions.md", "GEMINI.md"];
const CREATE_BY_DEFAULT = new Set(["AGENTS.md"]);

/** Replaces the marked block, or appends one. Everything outside the markers is returned byte for byte. */
export function syncBlock(existing: string | undefined, body: string, file: string): string {
  const block = `${START}\n${NOTE}\n${body.trim()}\n${END}`;
  if (existing === undefined) return `${header(file)}${block}\n`;
  const start = existing.indexOf(START);
  const end = existing.indexOf(END, start);
  if (start >= 0 && end >= 0) return existing.slice(0, start) + block + existing.slice(end + END.length);
  const sep = existing.length === 0 ? "" : existing.endsWith("\n\n") ? "" : existing.endsWith("\n") ? "\n" : "\n\n";
  return `${existing}${sep}${block}\n`;
}

// Cursor rule files need frontmatter to be picked up
const header = (file: string) => (file.endsWith(".mdc") ? "---\ndescription: The coding style to write in, served by idiolect\nalwaysApply: true\n---\n\n" : "");

export type SyncResult = { file: string; status: "created" | "updated" | "unchanged" | "skipped" };

/** With explicit targets every file is written. With none, known files are updated and only the ones in `create` are created. */
export async function syncTargets(repo: string, body: string, targets?: string[], create: ReadonlySet<string> = CREATE_BY_DEFAULT): Promise<SyncResult[]> {
  const explicit = !!targets;
  const out: SyncResult[] = [];
  for (const file of targets ?? DEFAULT_TARGETS) {
    const path = join(repo, file);
    const existing = await readFile(path, "utf8").catch(() => undefined);
    if (existing === undefined && !explicit && !create.has(file)) { out.push({ file, status: "skipped" }); continue; }
    const next = syncBlock(existing, body, file);
    if (next === existing) { out.push({ file, status: "unchanged" }); continue; }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, next);
    out.push({ file, status: existing === undefined ? "created" : "updated" });
  }
  return out;
}
